#!/usr/bin/env bash

# wrapper for datamodel-codegen
# generates pydantic v2 models from a schema file

# generate models
datamodel-codegen --input "$1" --output "$2/model.gen.py" \
    --output-model-type pydantic_v2.BaseModel \
    --field-constraints \
    --allow-population-by-field-name \
    --collapse-root-models \
    --use-default-kwarg \
    --enum-field-as-literal one \
    --use-field-description \
    --disable-timestamp

# run formatter
black "$2/model.gen.py"
